EconProject/__init__.py
import os
from flask import Flask, render_template, current_app
from flask_login import LoginManager
import secrets

from .views.home_view import bp as home_bp

def create_app(test_config=None):
    app = Flask(__name__)

    app.config.from_mapping(
        SECRET_KEY=secrets.token_urlsafe(32),
    )
    
    app.register_blueprint(home_bp)
    
    return app

EconProject/views/home_view.py
import os
from flask import Blueprint, current_app, flash, redirect, render_template, request, url_for

bp = Blueprint('home', __name__, url_prefix='/')

@bp.route('/')
def home():
    return render_template("index.html")

EconProject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body>
    <header>
        <nav id="main-nav">
            <div id="navOptions">
                <a href="{{ url_for('home.home') }}">Home</a>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    

        {% for message in get_flashed_messages() %}
            <div id="flash">
                {{message}}
            </div>
        {% endfor %}
    </main>
    <footer>
        <p>Luke Weaver | 1937361</p>
    </footer>
</body>

</html>

EconProject/templates/index.html
{% extends 'base.html' %}
{% block title %}Econ Project{% endblock %}

{% block content %}

{% endblock %}